### ISSUE TITLE
Request for review

### ISSUE THREAD

**Issue by Hombre2014** [Hombre2014/Catalog-of-my-things#32]
The Kanban project for our group is: [Catalog of my things](https://github.com/users/Hombre2014/projects/2)

We are a team of three people and the tasks are:
Team member #1 (Book and Label) - @AtillaTahak
Team member #2 (Music album and genre) - @Hombre2014 
Team member #3 (Game and Author) - @charlesgobina

**Comment by o-rashad** [comment]
Asslam Alaikum Team @Hombre2014 @AtillaTahak @charlesgobina  ,😊

Hi👋🏽, 
Your milestone is complete!  Good luck with the upcoming ones ^^!

# Congratulations! 🎉 

Happy coding!👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by charlesgobina** [comment]
Thank you @od-c0d3r

**Comment by Hombre2014** [comment]
Thanks for your quick review.
